import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { Pool } from 'pg';

const app = express();
app.use(cors());
app.use(helmet());
app.use(express.json({ limit: '1mb' }));

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

async function ensureSchema(){
  try {
    await pool.query(`create table if not exists public.states (
      id bigint generated by default as identity primary key,
      key text unique not null,
      payload jsonb not null,
      updated_at timestamptz not null default now()
    );`);
    await pool.query(`create index if not exists idx_states_key on public.states(key);`);
    await pool.query(`create table if not exists public.role_tests (
      id bigint generated by default as identity primary key,
      job_id text,
      job_title text,
      score int not null default 0,
      mcq_score int not null default 0,
      answers jsonb not null,
      ts bigint not null
    );`);
    await pool.query(`create index if not exists idx_role_tests_job_id on public.role_tests(job_id);`);
    await pool.query(`create index if not exists idx_role_tests_ts on public.role_tests(ts);`);
    await pool.query(`create table if not exists public.jobs (
      job_id text primary key,
      title text,
      location text,
      type text,
      openings int,
      team text,
      description text,
      created_at timestamptz not null default now()
    );`);
    await pool.query(`create table if not exists public.employees (
      id bigint generated by default as identity primary key,
      employee_id text,
      name text,
      job_id text,
      job_title text,
      status text,
      notes text,
      years int,
      skills jsonb,
      certs jsonb,
      source_company text,
      created_at timestamptz not null default now()
    );`);
    console.log('Schema ensured');
  } catch (e) {
    console.error('Failed to ensure schema', e.message);
  }
}

app.get('/api/health', async (req, res) => {
  res.json({ ok: true });
});

app.get('/api/state', async (req, res) => {
  try {
    const key = String(req.query.key || 'lumion_jobs_state');
    const q = await pool.query('select key, payload, updated_at from public.states where key = $1 limit 1', [key]);
    if (!q.rows.length) return res.status(404).json({ error: 'not_found' });
    res.json(q.rows[0]);
  } catch (e) {
    res.status(500).json({ error: 'server_error' });
  }
});

app.put('/api/state', async (req, res) => {
  try {
    const key = String(req.body.key || 'lumion_jobs_state');
    const payload = req.body.payload;
    if (payload == null) return res.status(400).json({ error: 'payload_required' });
    const up = await pool.query(
      'insert into public.states(key, payload) values ($1, $2) on conflict(key) do update set payload = excluded.payload, updated_at = now() returning key, payload, updated_at',
      [key, payload]
    );
    res.json(up.rows[0]);
  } catch (e) {
    res.status(500).json({ error: 'server_error' });
  }
});

app.post('/api/role-tests', async (req, res) => {
  try {
    const body = req.body || {};
    const job_id = body.job_id || (body.job && body.job.id) || null;
    const job_title = body.job_title || (body.job && body.job.title) || null;
    const score = Number(body.score || 0);
    const mcq_score = Number(body.mcq_score || 0);
    const answers = body.answers || {};
    const ts = Number(body.ts || Date.now());
    const ins = await pool.query(
      'insert into public.role_tests(job_id, job_title, score, mcq_score, answers, ts) values ($1, $2, $3, $4, $5, $6) returning id',
      [job_id, job_title, score, mcq_score, answers, ts]
    );
    res.status(201).json({ id: ins.rows[0].id });
  } catch (e) {
    res.status(500).json({ error: 'server_error' });
  }
});

app.post('/api/jobs', async (req, res) => {
  try {
    const job = req.body && req.body.job ? req.body.job : req.body;
    if(!job || !job.id) return res.status(400).json({ error: 'job_required' });
    await pool.query(
      'insert into public.jobs(job_id, title, location, type, openings, team, description) values ($1,$2,$3,$4,$5,$6,$7) on conflict(job_id) do update set title=excluded.title, location=excluded.location, type=excluded.type, openings=excluded.openings, team=excluded.team, description=excluded.description',
      [job.id, job.title||null, job.location||null, job.type||null, job.openings||0, job.team||null, job.description||null]
    );
    res.status(201).json({ ok: true });
  } catch (e) {
    res.status(500).json({ error: 'server_error' });
  }
});

app.post('/api/employees', async (req, res) => {
  try {
    const b = req.body || {};
    await pool.query(
      'insert into public.employees(employee_id, name, job_id, job_title, status, notes, years, skills, certs, source_company) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',
      [b.employee_id||null, b.name||null, b.job_id||null, b.job_title||null, b.status||null, b.notes||null, b.years||0, b.skills||[], b.certs||[], b.source_company||null]
    );
    res.status(201).json({ ok: true });
  } catch (e) {
    res.status(500).json({ error: 'server_error' });
  }
});

const port = Number(process.env.PORT || 8787);
ensureSchema().then(() => {
  app.listen(port, () => {
    console.log(`API listening on http://localhost:${port}`);
  });
});